### ISSUE TITLE
buttonset not a function

### ISSUE THREAD

**Issue by gfmclean** [vanderlee/fontpicker#1]
I am using JQuery UI v1.12.1 and at line 577 at:

$('.ui-fontpicker-buttonset', e).buttonset();

I am getting buttonset is not a function.  I tried to replace this with buttongroup, but still no good.

Can anyone help please?

**Comment by vanderlee** [comment]
jQueryUI deprecated `.buttonset()` and replaced it with the otherwise identical `.controlgroup()`. I'll update fontpicker to accept this.

**Comment by vanderlee** [comment]
Please check the most recent version.

**Comment by gfmclean** [comment]
Thank you very much for your response.  I shall look into it.
